In [2]:
import pandas as pd

In [6]:
tickets = pd.read_csv('datos/tickets_soporte_q1.csv')
clientes = pd.read_csv('datos/clientes_soporte.csv')
estados = pd.read_csv('datos/estados_ticket.csv')

print("Tickets")
display(tickets.head())

print("Clientes")
display(clientes.head())

print("Estados")
display(estados.head())

Tickets

,id_ticket,fec_apertura,id_cli,cat_incid,prio,st_cod,canal_orig,reg,hrs_res,nps
0,5001,2026-01-05,120,Entrega,Media,1,Web,CL,37.1,2.0
1,5002,2026-01-08,115,Entrega,Media,2,Tienda,MX,57.3,2.0
2,5003,2026-01-09,110,Producto,Alta,3,Web,AR,68.9,1.0
3,5004,2026-01-12,115,Producto,Baja,4,Tienda,CL,66.8,5.0
4,5005,2026-01-11,120,Facturación,Baja,5,Web,MX,34.1,1.0

Clientes

   id_cli  nombre_cliente   segmento
0     100  María González    Premium
1     101     Carlos Ruiz     Retail
2     102    Ana Martínez    Premium
3     103  Luis Fernández     Retail
4     104     Sofía López  Corporate

Estados

   st_cod estado_visible  es_final
0       1          Nuevo     False
1       2       Asignado     False
2       3       En curso     False
3       4       Resuelto      True
4       5        Cerrado      True

In [13]:
df = tickets.copy() # creamos una copia de Tickets en la varialble df, motivo preservar los datos orignales

df.head()

,id_ticket,fec_apertura,id_cli,cat_incid,prio,st_cod,canal_orig,reg,hrs_res,nps
0,5001,2026-01-05,120,Entrega,Media,1,Web,CL,37.1,2.0
1,5002,2026-01-08,115,Entrega,Media,2,Tienda,MX,57.3,2.0
2,5003,2026-01-09,110,Producto,Alta,3,Web,AR,68.9,1.0
3,5004,2026-01-12,115,Producto,Baja,4,Tienda,CL,66.8,5.0
4,5005,2026-01-11,120,Facturación,Baja,5,Web,MX,34.1,1.0

In [ ]:
df.info() 
# .info() nos muestra el los tipos de datos de cada columna
# la cantidad de datos no nulos
# la cantidad registros
# la memoria que ocupa el DF

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_ticket     50 non-null     int64
 1   fec_apertura  50 non-null     str
 2   id_cli        50 non-null     int64
 3   cat_incid     50 non-null     str
 4   prio          50 non-null     str
 5   st_cod        50 non-null     int64
 6   canal_orig    50 non-null     str
 7   reg           50 non-null     str
 8   hrs_res       47 non-null     float64
 9   nps           49 non-null     float64
dtypes: float64(2), int64(3), str(5)
memory usage: 4.0 KB

### Observaciones
- Cambiar el tipo de dato a `fec_apertura` por formato fecha
- Revisar lso datos nulso de `hrs_res` y de `nps`
- Cambiar el nombre de las columnas .... ID_Ticket ID Cliente, Il1 id_ticket

In [ ]:
display(df.describe().T)

        id_ticket      id_cli     st_cod    hrs_res        nps
count    50.00000   50.000000  50.000000  47.000000  49.000000
mean   5025.50000  109.540000   3.000000  30.323404   3.204082
std      14.57738    8.933336   1.428571  19.708244   1.471671
min    5001.00000  100.000000   1.000000   0.700000   1.000000
25%    5013.25000  102.000000   2.000000  15.400000   2.000000
50%    5025.50000  107.500000   3.000000  28.900000   3.000000
75%    5037.75000  115.000000   4.000000  43.750000   4.000000
max    5050.00000  130.000000   5.000000  68.900000   5.000000

In [16]:
display(df.describe().T)

,count,mean,std,min,25%,50%,75%,max
id_ticket,50.0,5025.500000,14.577380,5001.0,5013.25,5025.5,5037.75,5050.0
id_cli,50.0,109.540000,8.933336,100.0,102.00,107.5,115.00,130.0
st_cod,50.0,3.000000,1.428571,1.0,2.00,3.0,4.00,5.0
hrs_res,47.0,30.323404,19.708244,0.7,15.40,28.9,43.75,68.9
nps,49.0,3.204082,1.471671,1.0,2.00,3.0,4.00,5.0

- Revisar datos nulos de estas atributos (ejemplo id_ticket)
- Revisar los outliers (valores atipicos) de estas atributos (ejemplo id_ticket)
- Otros

In [19]:
df.head()

,id_ticket,fec_apertura,id_cli,cat_incid,prio,st_cod,canal_orig,reg,hrs_res,nps
0,5001,2026-01-05,120,Entrega,Media,1,Web,CL,37.1,2.0
1,5002,2026-01-08,115,Entrega,Media,2,Tienda,MX,57.3,2.0
2,5003,2026-01-09,110,Producto,Alta,3,Web,AR,68.9,1.0
3,5004,2026-01-12,115,Producto,Baja,4,Tienda,CL,66.8,5.0
4,5005,2026-01-11,120,Facturación,Baja,5,Web,MX,34.1,1.0

In [20]:
df.index

RangeIndex(start=0, stop=50, step=1)

In [21]:
df.columns

Index(['id_ticket', 'fec_apertura', 'id_cli', 'cat_incid', 'prio', 'st_cod',
       'canal_orig', 'reg', 'hrs_res', 'nps'],
      dtype='str')

In [30]:
df_1 = df.copy()
df_1 = df_1.rename(columns={
    "fec_apertura": "fecha_alta",
    "prio": "prioridad",
    "nps": "Net Promoter Score"
})

In [31]:
df_1.head()

,id_ticket,fecha_alta,id_cli,cat_incid,prioridad,st_cod,canal_orig,reg,hrs_res,Net Promoter Score
0,5001,2026-01-05,120,Entrega,Media,1,Web,CL,37.1,2.0
1,5002,2026-01-08,115,Entrega,Media,2,Tienda,MX,57.3,2.0
2,5003,2026-01-09,110,Producto,Alta,3,Web,AR,68.9,1.0
3,5004,2026-01-12,115,Producto,Baja,4,Tienda,CL,66.8,5.0
4,5005,2026-01-11,120,Facturación,Baja,5,Web,MX,34.1,1.0

In [32]:
df_1 = df_1.rename(columns={"Net Promoter Score":"nps"})

In [33]:
df_1.head()

,id_ticket,fecha_alta,id_cli,cat_incid,prioridad,st_cod,canal_orig,reg,hrs_res,nps
0,5001,2026-01-05,120,Entrega,Media,1,Web,CL,37.1,2.0
1,5002,2026-01-08,115,Entrega,Media,2,Tienda,MX,57.3,2.0
2,5003,2026-01-09,110,Producto,Alta,3,Web,AR,68.9,1.0
3,5004,2026-01-12,115,Producto,Baja,4,Tienda,CL,66.8,5.0
4,5005,2026-01-11,120,Facturación,Baja,5,Web,MX,34.1,1.0

In [34]:
df_1 = df_1.set_index("id_ticket")
df_1.head()

,fecha_alta,id_cli,cat_incid,prioridad,st_cod,canal_orig,reg,hrs_res,nps
id_ticket,,,,,,,,,
5001,2026-01-05,120,Entrega,Media,1,Web,CL,37.1,2.0
5002,2026-01-08,115,Entrega,Media,2,Tienda,MX,57.3,2.0
5003,2026-01-09,110,Producto,Alta,3,Web,AR,68.9,1.0
5004,2026-01-12,115,Producto,Baja,4,Tienda,CL,66.8,5.0
5005,2026-01-11,120,Facturación,Baja,5,Web,MX,34.1,1.0

In [ ]:
# df1 contiene nombres de columnas modificados
df_1.loc[5002]

fecha_alta    2026-01-08
id_cli               115
cat_incid        Entrega
prioridad          Media
st_cod                 2
canal_orig        Tienda
reg                   MX
hrs_res             57.3
nps                  2.0
Name: 5002, dtype: object

In [ ]:
# df es la primera copia de los datos originales de Tickets
df.loc[1]

id_ticket             5002
fec_apertura    2026-01-08
id_cli                 115
cat_incid          Entrega
prio                 Media
st_cod                   2
canal_orig          Tienda
reg                     MX
hrs_res               57.3
nps                    2.0
Name: 1, dtype: object

In [41]:
df_1.loc[5002, "cat_incid"]

'Entrega'

In [42]:
df_1.loc[5005, "canal_orig"]

'Web'

In [45]:
df_1.loc[[5002, 5005, 5030, 5041], ["id_cli", "fecha_alta", "canal_orig", "prioridad"]]

           id_cli  fecha_alta   canal_orig prioridad
id_ticket
5002          115  2026-01-08       Tienda     Media
5005          120  2026-01-11          Web      Baja
5030          110  2026-02-23  Marketplace      Alta
5041          102  2026-03-14       Tienda   Crítica

In [48]:
display(df_1.describe(include="str").T)
display(df_1.describe(include="number").T)
display(df_1.describe(include="all").T)

           count unique         top freq
fecha_alta    50     45  2026-01-15    2
cat_incid     50      6    Producto   12
prioridad     50      4        Alta   17
canal_orig    50      3         Web   24
reg           50      3          CL   18

         count        mean        std    min    25%    50%     75%    max
id_cli    50.0  109.540000   8.933336  100.0  102.0  107.5  115.00  130.0
st_cod    50.0    3.000000   1.428571    1.0    2.0    3.0    4.00    5.0
hrs_res   47.0   30.323404  19.708244    0.7   15.4   28.9   43.75   68.9
nps       49.0    3.204082   1.471671    1.0    2.0    3.0    4.00    5.0

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
fecha_alta,50,45,2026-01-15,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id_cli,50.0,NaN,NaN,NaN,109.54,8.933336,100.0,102.0,107.5,115.0,130.0
cat_incid,50,6,Producto,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prioridad,50,4,Alta,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
st_cod,50.0,NaN,NaN,NaN,3.0,1.428571,1.0,2.0,3.0,4.0,5.0
canal_orig,50,3,Web,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reg,50,3,CL,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hrs_res,47.0,NaN,NaN,NaN,30.323404,19.708244,0.7,15.4,28.9,43.75,68.9
nps,49.0,NaN,NaN,NaN,3.204082,1.471671,1.0,2.0,3.0,4.0,5.0

In [50]:
df_1.head()

,fecha_alta,id_cli,cat_incid,prioridad,st_cod,canal_orig,reg,hrs_res,nps
id_ticket,,,,,,,,,
5001,2026-01-05,120,Entrega,Media,1,Web,CL,37.1,2.0
5002,2026-01-08,115,Entrega,Media,2,Tienda,MX,57.3,2.0
5003,2026-01-09,110,Producto,Alta,3,Web,AR,68.9,1.0
5004,2026-01-12,115,Producto,Baja,4,Tienda,CL,66.8,5.0
5005,2026-01-11,120,Facturación,Baja,5,Web,MX,34.1,1.0

In [56]:
df_1.iloc[4, 2]

'Facturación'

In [ ]:
print("reg")
df_1.iloc[2:5, 2:7]

reg

           fecha_alta  id_cli    cat_incid prioridad  st_cod canal_orig
id_ticket
5001       2026-01-05     120      Entrega     Media       1        Web
5002       2026-01-08     115      Entrega     Media       2     Tienda
5003       2026-01-09     110     Producto      Alta       3        Web
5004       2026-01-12     115     Producto      Baja       4     Tienda
5005       2026-01-11     120  Facturación      Baja       5        Web

In [61]:
print("reg")
df_1.iloc[2:5, 2:7]

reg

             cat_incid prioridad  st_cod canal_orig reg
id_ticket
5003          Producto      Alta       3        Web  AR
5004          Producto      Baja       4     Tienda  CL
5005       Facturación      Baja       5        Web  MX

In [62]:
df_1.index

RangeIndex(start=5001, stop=5051, step=1, name='id_ticket')

In [66]:
df_1 = df_1.reset_index()

In [72]:
df_1.head()

,id_ticket,fecha_alta,id_cli,cat_incid,prioridad,st_cod,canal_orig,reg,hrs_res,nps
0,5001,2026-01-05,120,Entrega,Media,1,Web,CL,37.1,2.0
1,5002,2026-01-08,115,Entrega,Media,2,Tienda,MX,57.3,2.0
2,5003,2026-01-09,110,Producto,Alta,3,Web,AR,68.9,1.0
3,5004,2026-01-12,115,Producto,Baja,4,Tienda,CL,66.8,5.0
4,5005,2026-01-11,120,Facturación,Baja,5,Web,MX,34.1,1.0

In [71]:
region = df_1[df_1["reg"] == "MX"]
region

,id_ticket,fecha_alta,id_cli,cat_incid,prioridad,st_cod,canal_orig,reg,hrs_res,nps
1,5002,2026-01-08,115,Entrega,Media,2,Tienda,MX,57.3,2.0
4,5005,2026-01-11,120,Facturación,Baja,5,Web,MX,34.1,1.0
7,5008,2026-01-16,107,Entrega,Baja,3,Marketplace,MX,51.7,1.0
20,5021,2026-02-07,109,Técnico,Baja,1,Marketplace,MX,14.9,1.0
22,5023,2026-02-12,115,Producto,Alta,3,Marketplace,MX,3.5,3.0
23,5024,2026-02-13,108,Producto,Alta,4,Tienda,MX,43.5,3.0
25,5026,2026-02-17,108,Cuenta,Media,1,Web,MX,5.9,4.0
29,5030,2026-02-23,110,Técnico,Alta,5,Marketplace,MX,15.9,5.0
30,5031,2026-02-26,109,Devolución,Crítica,1,Marketplace,MX,34.9,3.0
36,5037,2026-03-06,100,Entrega,Baja,2,Marketplace,MX,45.5,3.0
40,5041,2026-03-14,102,Entrega,Crítica,1,Tienda,MX,6.3,2.0
42,5043,2026-03-17,102,Cuenta,Media,3,Web,MX,1.2,1.0
43,5044,2026-03-17,107,Producto,Media,4,Marketplace,MX,4.7,NaN
44,5045,2026-03-20,104,Devolución,Crítica,5,Web,MX,7.9,5.0
45,5046,2026-03-21,103,Cuenta,Alta,1,Web,MX,30.8,2.0
48,5049,2026-03-27,100,Producto,Crítica,4,Web,MX,33.7,3.0

In [73]:
region.info()

<class 'pandas.DataFrame'>
Index: 16 entries, 1 to 48
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_ticket   16 non-null     int64
 1   fecha_alta  16 non-null     str
 2   id_cli      16 non-null     int64
 3   cat_incid   16 non-null     str
 4   prioridad   16 non-null     str
 5   st_cod      16 non-null     int64
 6   canal_orig  16 non-null     str
 7   reg         16 non-null     str
 8   hrs_res     16 non-null     float64
 9   nps         15 non-null     float64
dtypes: float64(2), int64(3), str(5)
memory usage: 1.4 KB

In [74]:
tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_ticket     50 non-null     int64
 1   fec_apertura  50 non-null     str
 2   id_cli        50 non-null     int64
 3   cat_incid     50 non-null     str
 4   prio          50 non-null     str
 5   st_cod        50 non-null     int64
 6   canal_orig    50 non-null     str
 7   reg           50 non-null     str
 8   hrs_res       47 non-null     float64
 9   nps           49 non-null     float64
dtypes: float64(2), int64(3), str(5)
memory usage: 4.0 KB

In [77]:
tickets.sample(5)

,id_ticket,fec_apertura,id_cli,cat_incid,prio,st_cod,canal_orig,reg,hrs_res,nps
20,5021,2026-02-07,109,Técnico,Baja,1,Marketplace,MX,14.9,1.0
17,5018,2026-02-03,104,Técnico,Alta,3,Tienda,AR,18.4,4.0
6,5007,2026-01-15,105,Devolución,Alta,2,Tienda,CL,26.6,4.0
34,5035,2026-03-02,102,Devolución,Alta,5,Tienda,CL,17.5,4.0
16,5017,2026-01-31,110,Facturación,Alta,2,Marketplace,AR,10.5,4.0

In [75]:
clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cli          15 non-null     int64
 1   nombre_cliente  15 non-null     str
 2   segmento        15 non-null     str
dtypes: int64(1), str(2)
memory usage: 492.0 bytes

In [76]:
estados.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   st_cod          5 non-null      int64
 1   estado_visible  5 non-null      str
 2   es_final        5 non-null      bool
dtypes: bool(1), int64(1), str(1)
memory usage: 217.0 bytes